# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from rootcollection.decorators import lazy_property
from rootcollection.configuration import Configuration
from rootcollection.configuration import Environment
from rootcollection.http.auth.o_auth_2 import OAuth2
from rootcollection.controllers.accounts_controller import AccountsController
from rootcollection.controllers.locataire_controller import LocataireController
from rootcollection.controllers.login_controller import LoginController
from rootcollection.controllers.reset_controller import ResetController
from rootcollection.controllers.settings_controller import SettingsController
from rootcollection.controllers.signup_controller import SignupController
from rootcollection.controllers.upload_controller import UploadController


class RootcollectionClient(object):

    auth = OAuth2

    @lazy_property
    def accounts(self):
        return AccountsController(self.config, self.auth_managers)

    @lazy_property
    def locataire(self):
        return LocataireController(self.config, self.auth_managers)

    @lazy_property
    def login(self):
        return LoginController(self.config, self.auth_managers)

    @lazy_property
    def reset(self):
        return ResetController(self.config, self.auth_managers)

    @lazy_property
    def settings(self):
        return SettingsController(self.config, self.auth_managers)

    @lazy_property
    def signup(self):
        return SignupController(self.config, self.auth_managers)

    @lazy_property
    def upload(self):
        return UploadController(self.config, self.auth_managers)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION, access_token='',
                 config=None):
        if config is None:
            self.config = Configuration(
                                         http_client_instance=http_client_instance,
                                         override_http_client_configuration=override_http_client_configuration,
                                         http_call_back=http_call_back,
                                         timeout=timeout,
                                         max_retries=max_retries,
                                         backoff_factor=backoff_factor,
                                         retry_statuses=retry_statuses,
                                         retry_methods=retry_methods,
                                         environment=environment,
                                         access_token=access_token)
        else:
            self.config = config
        self.initialize_auth_managers(self.config)

    def initialize_auth_managers(self, config):
        self.auth_managers = { key: None for key in ['global']}
        self.auth_managers['global'] = OAuth2(config.access_token)
        return self.auth_managers
