# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from rootcollection.api_helper import APIHelper


class LocataireControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(LocataireControllerTests, cls).setUpClass()
        cls.controller = cls.client.locataire
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_validated
    def test_validated(self):

        # Perform the API call through the SDK function
        self.controller.validated()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_waiting
    def test_waiting(self):

        # Perform the API call through the SDK function
        self.controller.waiting()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_rejected
    def test_rejected(self):

        # Perform the API call through the SDK function
        self.controller.rejected()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

