# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from rootcollection.api_helper import APIHelper


class UploadControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(UploadControllerTests, cls).setUpClass()
        cls.controller = cls.client.upload
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_upload
    def test_upload(self):

        # Perform the API call through the SDK function
        self.controller.upload()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

