# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from rootcollection.api_helper import APIHelper
from rootcollection.models.delete_locataire_request import DeleteLocataireRequest


class AccountsControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(AccountsControllerTests, cls).setUpClass()
        cls.controller = cls.client.accounts
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_delete_locataire
    def test_delete_locataire(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"email":"agent1@nexcode.dz"}', DeleteLocataireRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.delete_locataire(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

