# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from rootcollection.api_helper import APIHelper
from rootcollection.models.reset_password_locataire_request import ResetPasswordLocataireRequest
from rootcollection.models.delete_locataire_request import DeleteLocataireRequest


class SettingsControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(SettingsControllerTests, cls).setUpClass()
        cls.controller = cls.client.settings
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_update_locataire_password
    def test_update_locataire_password(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"password":"passwordupdated"}', ResetPasswordLocataireRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.update_locataire_password(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_update_agent_password
    def test_update_agent_password(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"password":"passwordupdated"}', ResetPasswordLocataireRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.update_agent_password(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_update_decideur_password
    def test_update_decideur_password(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"password":"passwordupdated"}', ResetPasswordLocataireRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.update_decideur_password(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_update_locataire_email
    def test_update_locataire_email(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"password":"passwordupdated"}', ResetPasswordLocataireRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.update_locataire_email(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_update_decideur_email
    def test_update_decideur_email(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"email":"dec@gmail.com"}', DeleteLocataireRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.update_decideur_email(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_update_agent_email
    def test_update_agent_email(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"email":"agent@gmail.com"}', DeleteLocataireRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.update_agent_email(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

