# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from rootcollection.api_helper import APIHelper
from rootcollection.models.locataire_login_request import LocataireLoginRequest


class LoginControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(LoginControllerTests, cls).setUpClass()
        cls.controller = cls.client.login
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_locataire_login
    def test_locataire_login(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"email":"im_gouaouri@esi.dz","password":"password"}', LocataireLoginRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.locataire_login(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_am_login
    def test_am_login(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"email":"ia_yalaoui@esi.dz","password":"resetreset"}', LocataireLoginRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.am_login(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_admin_login
    def test_admin_login(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"email":"admin@nexcode.dz","password":"password"}', LocataireLoginRequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.admin_login(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

