# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ForgotPasswordAM(object):

    """Implementation of the 'forgot_password_AM' model.

    TODO: type model description here.

    Attributes:
        message (string): TODO: type description here.
        success (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message": 'message',
        "success": 'success'
    }

    def __init__(self,
                 message=None,
                 success=None):
        """Constructor for the ForgotPasswordAM class"""

        # Initialize members of the class
        self.message = message
        self.success = success

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        message = dictionary.get('message')
        success = dictionary.get('success')

        # Return an object of this model
        return cls(message,
                   success)
