# -*- coding: utf-8 -*-

"""
rootcollection

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RejectLocataireRequest(object):

    """Implementation of the 'reject_locataire_request' model.

    TODO: type model description here.

    Attributes:
        email (string): TODO: type description here.
        justificatif (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email": 'email',
        "justificatif": 'justificatif'
    }

    def __init__(self,
                 email=None,
                 justificatif=None):
        """Constructor for the RejectLocataireRequest class"""

        # Initialize members of the class
        self.email = email
        self.justificatif = justificatif

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        email = dictionary.get('email')
        justificatif = dictionary.get('justificatif')

        # Return an object of this model
        return cls(email,
                   justificatif)
